apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-spark-pv
  labels:
    type: local
    app: my-spark
    project: simple-spark-cluster
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-spark-pvc
  labels:
    app: my-spark
    project: simple-spark-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Change accordingly